version: "3"

services:
  frontend:
    build:
      context: ./frontend
    networks:
      net:
        ipv4_address: 193.168.1.20

  retrocrypto_api:
    build:
      context: ./retrocrypto
    networks:
      net:
        ipv4_address: 193.168.1.30
    volumes:
      - ./ssl:/etc/ssl

  selftrack_api:
    build:
      context: ./selftrack
    networks:
      net:
        ipv4_address: 193.168.1.40
    volumes:
      - ./ssl:/etc/ssl



  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
      - ./nginx/runtime_logs:/var/log/nginx
    networks:
      net:
        ipv4_address: 193.168.1.10
    depends_on:
      - frontend
      - retrocrypto_api
      - selftrack_api

networks:
  net:
    ipam:
      config:
        - subnet: 193.168.1.0/24
      
